from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from pptx import Presentation
from pptx.util import Inches as PptxInches, Pt as PptxPt

class DocumentService:
    
    def create_docx(self, content, file_buffer):
        """Create a Word document from content dictionary."""
        
        doc = Document()
        
        # Add title
        title = doc.add_heading(content.get('title', 'Untitled Document'), 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Add sections
        for section in content.get('sections', []):
            # Add section heading
            doc.add_heading(section.get('title', 'Untitled Section'), 1)
            
            # Add section content
            section_content = section.get('content', '')
            
            # Split into paragraphs if the content contains newlines
            paragraphs = section_content.split('\n\n') if '\n\n' in section_content else [section_content]
            
            for para_text in paragraphs:
                if para_text.strip():
                    paragraph = doc.add_paragraph(para_text.strip())
                    paragraph.paragraph_format.line_spacing = 1.5
            
            # Add spacing after section
            doc.add_paragraph()
        
        # Save to buffer
        doc.save(file_buffer)
    
    def create_pptx(self, content, file_buffer):
        """Create a PowerPoint presentation from content dictionary."""
        
        prs = Presentation()
        prs.slide_width = PptxInches(10)
        prs.slide_height = PptxInches(7.5)
        
        # Title slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        
        title.text = content.get('title', 'Untitled Presentation')
        subtitle.text = "Generated by Ocean AI"
        
        # Content slides
        for slide_content in content.get('slides', []):
            bullet_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_slide_layout)
            
            shapes = slide.shapes
            title_shape = shapes.title
            body_shape = shapes.placeholders[1]
            
            title_shape.text = slide_content.get('title', 'Untitled Slide')
            
            text_frame = body_shape.text_frame
            text_frame.clear()
            
            # Add bullet points
            bullet_points = slide_content.get('content', [])
            if isinstance(bullet_points, str):
                bullet_points = [bullet_points]
            
            for i, point in enumerate(bullet_points):
                if i == 0:
                    text_frame.text = point
                else:
                    p = text_frame.add_paragraph()
                    p.text = point
                    p.level = 0
        
        # Save to buffer
        prs.save(file_buffer)
